[package]
name = "dbc-data-derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
can-dbc = "6.0.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
