[package]
name = "dbc-data"
version = "0.1.0"
edition = "2024"
authors = ["Michael Fairman <mfairman@tegimeki.com>"]
readme = "README.md"
description = "Derive macro for CAN DBC code generation"
repository = "https://gitlab.com/mfairman/dbc-data"
license = "MIT"


[dependencies]
dbc-data-derive = { path = "dbc-data-derive" }
