[package]
name = "dbc-data"
version = "0.1.3"
edition = "2024"
authors = ["Michael Fairman <mfairman@tegimeki.com>"]
readme = "README.md"
description = "Derive macro for CAN DBC code generation"
repository = "https://gitlab.com/mfairman/dbc-data"
keywords = ["can", "automotive", "ecu", "no-std"]
license = "MIT"


[lib]
proc-macro = true

[dev-dependencies]
assert_hex = "0.4.1"

[dependencies]
can-dbc = "6.0.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
